#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2024/03/13 06:19:54
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.rsds.gn.v20200619|esgf-data1.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.rsds.gn.v20200619|esgf-data1.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'SHA256' '8a658e026d423eddcf5d4c5a557731a7eba399bbabdb0b918e5b1ce61712f705'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'SHA256' 'c2eb6c92971cf29da150819e02ced6fccd7ebbb54651c0a4b52760c40118b580'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'SHA256' '6a65a9c3d05320dafbccf6dfed27080a73592cea0321e79db0b0fd2fb2e8b612'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'SHA256' '66926cfefbd2c89dbece3dfe16f66c69eabd3074e6bcef0eb561d131e718be81'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'SHA256' '902d02b70f48880dca5827badb15ca46aaccfe4c0f4d0fd700c5a533ea9b53c7'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'SHA256' 'c2fcd1c1ff050b1fd4a43e083280a15695aa6300fb8c129b2c8f5f012b7473f0'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'SHA256' 'd66edf2c628e7282277ea3ede0b8e73f3e5fac38d469706add2b653974b22bef'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'SHA256' '4911323624080e675f6f59ce869f1b5275b0143f8a3576cd24b4252bd891efa9'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'SHA256' '25200aa6e1a6573711b19d5f757fc80a1e9f66f776644e410b96be84956a6d19'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'SHA256' '71e6342ad7456b2ed46cb00d2cb362b15674f701b8e720333bd0e1c38a04d361'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'SHA256' '6c3158cc80a31c1f511cfc6e86a5c705fbebfea15e0fdd87e874b0cbfba8132f'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'SHA256' '4373b703853ad863f3d554c3691663e0b10021cce195084073fe11608d0577b7'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'SHA256' 'b756d0579d6e80281941cd6b492fb953c4ab02de51eb0d62fa1e6b1027163764'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'SHA256' 'bf739ce8de7b797d0a2f0bd883126f875b6e7570dd578231ee7ce155b7503d22'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'SHA256' '7c85b3413c079a456e4ab768f8de81ed4f6115a01a16eb5fc7194f5d2ce8d9cf'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'SHA256' '785d74120e8bfb2832decf72f71b7d677b6dd5fba7fcd55b102e5174b63cf5b5'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'SHA256' '24c61f712d1b0c140ec38c89bf2531a2000df2d1b213460d7672761224c07992'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'SHA256' 'aa3e2002a909de21dfa62b9952d78aa72afb441757cf40114ae8002dc6538902'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'SHA256' 'bd11c08018b5cd9c42cb0d55f6968e71d00d926ee164cd679f9d924e5ecba55a'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'SHA256' 'bf639987326cc95e531d0891cfcd95b5189811c36aa672db467fada7619cfd94'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'SHA256' '5522049bdb93c55b6b467b871df2638ee3d624637a3e8138cdd20bc7fe2c86df'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'SHA256' '44a8a82dba178d1261ef6393ed905d494b3e134a01f276ef26728cfc6c8c3b2e'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'SHA256' '9e2c5c43338614c4081cc24b02b20c8ba070fba4b23e2a007f99018baa3e5c41'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'SHA256' '07cba5f6b68a3a0cbdfdcf4b6262acc7919e46df41ed38bdfd08146309269ede'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'SHA256' '01ea0a9ded89bef48cb6cf8eb9360c72e695b5eb16b4b7cc1d051735677db305'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'SHA256' '1a267dab747c1eb9362903c89fb83f003b63f95a07a58aa61907618363c7d5dd'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'SHA256' '014eebcd614c7f6d89e44d737e4fd34f15fc52a9dfcc94f96df6f04c2152f091'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'SHA256' '7c6efb104dccad755af3d9724df3c039e9898e50bd407b711e8369e003f34899'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'SHA256' '92c1ee4ad9e843fb498f406c71449633556566907e9a3e9723c4ed28b1c5755a'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'SHA256' '2fdd88e3ce7de086e53cb6b02cc1f2c7d88c4127a6edf98ac99d23c6e04a1fde'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'SHA256' '5a0722ea91d1e5a6583d2e2bd000a7675599c75383305aadf05bebe5c217bfc2'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'SHA256' '1274c06c077c5e6067f93faab120d2c9a00ba136991043844777d5c1975a7c11'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'SHA256' 'ca82d6b9eedd5f80a555f9d2f5fc31a179f31ae0c18e629feb13653bd1e02aa0'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'SHA256' '49a1cecebd70aa3a3f2dd5f9791fbdcdf3b33ae7d367a2067062a5da0445640d'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'SHA256' 'e4f0f68dd222cc0a426cc84556502b14cbff98ef8ba02107a4f4245b7250957f'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'SHA256' 'a1091d3faa4235c5bd13710976d75a9c34b90dbc44c4347bad4617c9cfbd47dd'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'SHA256' '2d1b356f61ac656f2152f000c26f504a8fc8513df4011b7fa1e6e0670db9b81d'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'SHA256' '98b9b149d733a3e96458c88451842dd055564cf35a4cd53f0258067abdb70d6a'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'SHA256' '4592f6b6836891bba3ecfeab506690eb8d6e86f30ac323c2e7a54cc2cb69abda'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'SHA256' 'de2bbf41f5cdc9fd3714842e8606f23869521f854eff8bedaf880043805094b1'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'SHA256' '35cc6b859f2e77783f17d079d0e19525bf2f80cec4873b960f5dded4ab1823b2'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'SHA256' '0128c6089a2da20d2938d07814103f84d962dfc63f5fbb2600b299a6c6bdbf81'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'SHA256' '3718a8bec587e7157bd71848bc822900bb3a8f63bda5c9eeb80d5cc66b9226f0'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'SHA256' '4d80422f7473800b486ff3f10078a61066e4cfdf604741f8d39119a874b2f85c'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'SHA256' 'e5c4104f3a6e978783e1405024dc040803014f694d43f5e75b898b6ed4f0f7be'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'SHA256' 'c73731efad1dbd8de4f98a0f0c4e881e2d77d2c3a5376e1e6317629707eb919f'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'SHA256' 'dc23828242932231078fb922e1d22dabf9c7d2312f95ae9dcd2a5664aeb36830'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'SHA256' '00a95ea6418d5d281811d6c4b29e7b5a17bfde2d339c6d8acea27ca7ba118bfa'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'SHA256' '5bc4911d719f16cec6c8b161913bdef23ce2d874b5d889a16256f9d22a9bb6b8'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'SHA256' 'bd1ebb843d30ee190710ee786091ce0ee65e635df6f1d895980280350a1a5655'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'SHA256' 'd0613d39bdecaffb364a533b6bd69d8923a40595c57012c1513cc84ef2dbab4e'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'SHA256' '30c1d066f8773719f5390668a65d0df0951dd0931c5f1c5baf3f73c372bf7f1a'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'SHA256' '1a29efb4b690339c41984e8b312a9969118eb1ecea1d9bd9b0f4851f3232621b'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'SHA256' 'bf90fc2173c5932c26fde71824d40cf0c44d55bb32dccecfd5140cd49178f21b'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'SHA256' '063ace605d4a87b189b843ddb764056d6c043c912c23d62d3a578b34344ae759'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'SHA256' '1178627d66b33667072325d59c4a64c810a90cf316db42db75c3b2fb56d18261'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'SHA256' 'acf4f7a16eb47e075bddc5be5bff6328d083240593ffba1cdaa421af85512bdf'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'SHA256' '1f2dd6758965cb6e3d3c647a6c3a8f08b111c84172e97cc84c1236d33944e1df'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'SHA256' 'd41dcc337a279233970b6e1069cbdc027cf51437a57478a0424a1030b93ca10b'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'SHA256' 'a3ef6b9c2e5d5ef48ecbc1fb70dc4462f43852072efa90036f17a285f5be1228'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'SHA256' '61416f86effae51ff8d41f3eb9492093af81e26111fcbba9d7e960ceac0f1a54'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'SHA256' 'a45149e8c53c05da7647e895d27c52246c07dfbc49d6da2c1071f09fd01bb0ed'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'SHA256' 'e2103e304914d5b88843002960bb2c9060ae690922fdace778400e57272f8e4f'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'SHA256' '72b0dd3774214343de00c88232720979f78c0667223f22aab2dd01a69d717467'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'SHA256' 'c338110c9b95150391d47760b522c5ca429c2968fbbe45d8143ca03657bbd987'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'SHA256' 'cb6ad99ce1a2e5dd99c97f27cbb2da8179ca376a690e0b67767360595f82ed67'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'SHA256' 'f6a3f6875d13b92b65f4e8d460b08c6ef86a17a30221c803f7fd1f6f42eee338'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'SHA256' '7fd91d2f825caaf4607cb81482fb9940699ba5340d401441d0e1984aeef3e9df'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'SHA256' '301f539b99043ecd024b362e34dab56ea2fbf6ce72a44535055333e82d8b00a2'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'SHA256' 'c561be7548fe088d2e8a61ca12fc11687fbd8659c3a78c950230d6e7068d5716'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'SHA256' '6995fb9c6de81086ea0967e11482c7106d5ed1dcf81bb9ffbe0710c087974eb7'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'SHA256' '343309ff9458d621cf7419e8caa2ba406f442e2de8b5bedac9c1ceb293783098'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'SHA256' 'cdcd09d86db654a9680048574de710db7089a98803fccc42dfc1296646543c92'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'SHA256' '5d5e19c1b1b675c7ec368bd3b26d08fbcae1c045a37d62d6ed46f5e0b4a6c37f'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'SHA256' '8f700426c7944caf18c785c5df4715c3225b2b1575a23f81f7f3a3e8f46f7248'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'SHA256' '67b8b45cf7ac2a4f788e2305b2fe1fc52ee89999495c10c5ed4e84ac8900a0bf'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'SHA256' '0f65f9ec5300caaefb6a178d7bb8c0136502cdda868c2f8eda6e9eda3f2f08e4'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'SHA256' '5e8d8fd75bd24690244be59998f3746b68fe9db0b6757414f02d942930bd6125'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'SHA256' 'f04b06d38007fb73b2d5cffab3b7c1e007433fbf772add1d0e6f2e34e718e1df'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'SHA256' '85f00e948fd777c62b924d0c158c60d77c199e6d3c7b5fc38d4a0f44721cbf6b'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'SHA256' '682558e99eccd2f86d6aa2051bf7f9ee4914e31642c04774554e8636eead2b8c'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'SHA256' 'e86f200110c2a88270363ecdc93584beff8db83694bccee0eb0d24ddf310e58e'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'SHA256' '00621a8b77347a8e0e7d54e8d66b74ecc3c2b51dd5c985ec5d36a55055b3a994'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'SHA256' '11c52f78875117b8c28b467e6f07656dbd4d23e4cef09eba06cebbaf57924d87'
'rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/rsds/gn/v20200619/rsds_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'SHA256' 'a6169b4a7154f8b1692655da971f583b162e3eceeeeb76a36d23ef8cdabe22ec'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 85 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
