#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2024/03/13 06:19:11
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.prsn.gn.v20200619|esgf-data1.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.prsn.gn.v20200619|esgf-data1.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'SHA256' '535e8764192ff0510dbefb3c25d4fc1723c98dc2d20e48b44663641f762cc60c'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'SHA256' '8c0d80244ce845de2973fc22a1cf266e68aad00efb3f340fc78105d4d2dbe53c'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'SHA256' '36c14e1ef27591d62cb2475f2d80f71b1e34e4d1d069ec626096f22c59c5db57'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'SHA256' '5e5acb52b48116300b9a1ae23b7688e45bcfb4749e0ec2d0cf2ded977ed222b5'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'SHA256' 'ee276cf700ca473a196f5a8268cd983d753141460b733a2ddae5d04fc6aba5b8'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'SHA256' 'e3fae13522bfcd9cc663cf5d2254cec2c5f0bcb4564caf7698b58b26e5fe9c0a'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'SHA256' 'f37236c7cf4116c146a4f68c4de94ef76ed6ca478aa708ef111abf1f2121fbf0'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'SHA256' '153b8b27610535418fff0b629020ac50ed05b83289643915ad50cd9914a93ba2'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'SHA256' '0b1041120e86f9c14b380c9b1975a09e423340b5c1736e6e2ebe489a266125a9'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'SHA256' '4d44516ec786b24d10b59e19453809b6efd2261c2b3e2fb056cc5734f20a06e8'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'SHA256' '3e4e44131f57137d8d3e302bdf4f4e7a300cdf626918b3d891cc1164b2b485dc'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'SHA256' 'f2c9dd82ee4e042d99efb1db1364ad1d5c2063c423e759f114ba248baf61cdc4'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'SHA256' 'dfcbb399b76cc4b8d849cb59b86e51a290aaaa59d8958985a541b5bcd91133ed'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'SHA256' '1eefcb5c21c5cd96abc369c58f9dedc14e7f4d85193121b6ced794262fc0b0c3'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'SHA256' '0fcdbb8c7fd3cc871a8cebf4f25f548a18aeda1be01630679b754a528d43a775'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'SHA256' 'cbeb1b994914855c5206bf50b3dd228a16610205a3c6574738ae284b9e1eb724'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'SHA256' '66b2459681873dd8510afc97020c60b4ced718afc2433a56c34a9f12e7bd861c'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'SHA256' '10c3bbda9207f70246782c2da3fb02a28a505dcca596a3c67d7ac7dffd2ee5ac'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'SHA256' 'bd459b31b1eb631d3b4d27154badca035a29f0012cb80002c1c5d065b7b51eaf'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'SHA256' '5f9e7a7fdce653848f1397be0d1ca9f09c9cd680f504d86199618485aa5ec91c'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'SHA256' '15a26e98b9d41b3c9bb27def76385e046471d46a97b961c2bf6a46f0c2745a8f'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'SHA256' '3ba3d2229e5fa4f6a0fc75665395898a527ed8feee55763b781e4b2ed5f1faa0'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'SHA256' '7058916d339cf9f83b7e1dc2eaa85ff2e3b2a0ed276115cf68b7809be062691a'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'SHA256' '9d1c9b2a08423ba48a1e6909a3dbc1f204708453c5e91f5dbd60dba616ac8b76'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'SHA256' '2b83855afde5a27f06c0794903af8516aea556b923758fa19e7876435a2e8e84'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'SHA256' '36a06177740c14d164bc154f76c40f20baf0246afe9148b8153c2693c5f86515'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'SHA256' 'ca4094611d78982bebbe28ca927ac3523a2ed542d65c39cadc98e75ba120f3dd'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'SHA256' 'e766cfb84effae2b16bb514996163371645099d2897cd5fe6e483980db3bd6d3'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'SHA256' 'b5fc52f7793010e52dcae36c27b96747f130bf74a3067c1b3254952400dfcdee'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'SHA256' '24c10f7a9ee0933734f708058d7762ac4214b85ec1174151759d2a755d49cf19'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'SHA256' '72ffa703fd1678ce21daa1ad7285ac00ee197aa5fbea2896f89ac98a547ad187'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'SHA256' '198575979e56f7227c1322b2a035f17ef8fa79663329cca41d84f81601d42e79'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'SHA256' '00b04b3a6ad178567973e78785aa024bcaedf299848ab580a114c28836f005db'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'SHA256' '42798296bdc75f360606811d9c3393e69d5e698c35bb53a84e7c497c8861d91b'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'SHA256' '40bf7c0c21f0f799fed3c263a07bab4d86cbb2bae9ef19e1f46598fcfe1b5ff8'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'SHA256' '6a315074a7129204d99c577785ea55a034c54ee572dd75e81ff5e15a3dc9e231'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'SHA256' 'eb5cdca9235d751983ada3855de05c9642226271e439153e0c249968babaae3a'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'SHA256' '386c0c7ef67567c82da1e45643d63a8031726b07db5d1b2a0a4a948be3a20e67'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'SHA256' '6d0951f5c10e2a23b786f92c062cfcf0c4bab0530a6fed53d87a2385e4688813'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'SHA256' 'adac9dbe8f5a63d0b672f2c24534c2bfdc9585f006794fc18138d239b79794c4'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'SHA256' '25a22160c1b8dade03c9fc382a1d7e43ab9e9b59f2cb0f0223f7917a9dc518cb'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'SHA256' '3e5f9f4fbf61aee2c0d6bdf26c4b829c6dbf6b6eba0751a3503ea9c9dc319667'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'SHA256' 'ac561b00e7417aa241167a25ff51f8bb6f07f764b4f7afe821c4c169fbac2745'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'SHA256' 'cc114e777d977f31888cb761d33307bb46f469ec6659992f9a91b84b9283aaca'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'SHA256' '45d9f1e40cf5fe476b94ed90bd472fc8123d3320bfb84506d71d97506e4eba76'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'SHA256' 'f280122722a4dbf1a210747962608fe5819cb9e976df5ae2de24f4f2ed8494e4'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'SHA256' '91ec744f8721226ef2a940d468df1b831e4a75cfcc19e37f6e80be7d3edafff9'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'SHA256' '87c0ad13c12bb0abc4b9fd6490c335ca715a50ad01522b586b4a2b8a09a0c3cf'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'SHA256' '40006acb0bd79517982ca4cf49ac8176b93f7fc0a6fdabc999d181af0a5599dd'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'SHA256' '569650841f110d063c5550598706331f442081907a14679a83f2df7dae100944'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'SHA256' 'd206f47a401ef04f5f4918c03e797d3f7285d9340aeeb1264297497e3f7f65ec'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'SHA256' '7d2120b231bef474074aa2e5af7cc819323c04bd38b7d6e70e3ce125680ac49e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'SHA256' '1f4b976b923e28f779e6f66c34f9ee057e8e71aefaf87b543f29de7e1cc9e94e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'SHA256' 'db745e2a57003a8a57eff0917a02fbb5c4981cda1197889b7b7b7f97c7932a18'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'SHA256' 'a806f4f701278e03387569f39df96ea5ed23e88e4a5b1f996bf2ad3282c0668e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'SHA256' 'fb4debd91cf42f8d142254dbea2f7ab22b21034b38cdb77c96ac2901d5c41c1a'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'SHA256' '732383467630271e6beb80f37a4e42866d45f451f46e613c6255bb57394811c0'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'SHA256' '8a34016240d6c7aac33a0a04268dd1083fa52875dd46416a943cd63e4666066c'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'SHA256' '37511169e8483c56def4e80140b07553b4a87a6619864564abcd9f85ac6e662e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'SHA256' 'ed386bb3b74b7a2dad8ddf5959ce412779320dca030c3aff404f47f651dfc726'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'SHA256' 'ab270099df27f8c8b98a8edc1b0865df7ce423be72a072aaf64be7234801f0b5'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'SHA256' '0046e674cf7cb69b1cf3ab6a6f1ab9a7e07788b1c0fedc042c25984de86b1662'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'SHA256' 'fb9dff02ad15574b809c692fe76fad46a5d8fc1eb60697a07bbaae2b96fb2fc6'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'SHA256' '6c297ee8f4acb92660496374fcc5431d5e96e545a7144f2fd438eb6893c626b1'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'SHA256' '0ce06f028860039e5df085cf429daa07d2279603aae4f7fbe712d2234382f977'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'SHA256' 'dfc736670106a69a972a9157f09fbcdf593de1ae0c57d02be0228d432c52aa3e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'SHA256' '24e638bb9b058993731ce136cb6e4e9d44eba54a97007d36968e9573aec5fd35'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'SHA256' 'b3834a4fffb5170686ebdc9e36560a3202d643903b3c52ca024d9de6c5d65288'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'SHA256' '243e5f9ddbce21f08cf0f60d66578c78954df1e34ad3fda9193ec4430d0645a9'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'SHA256' '9d3083f630fbcc764919f585e7d8a056f95f0040e7f34eb0dc4d94858d4d4b6e'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'SHA256' '1950cdc399497c9f767ace4de5c2807e9ad979d0503e0920abf469a0d48a60a7'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'SHA256' '6d63854ae69acc3b4198ceb0fafb0ece6337a7d34145a754650d00bd592e97f3'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'SHA256' '68e3f57a7007385dafc06ecc77fd0d5058603fb71f4a7c5b6be6e58c941956ce'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'SHA256' '1b7b21908221854e59cc60ce3d599f7ce5ca2e30dc776de9a0a4cf2a5df192b3'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'SHA256' 'af8321c9c6ecc95e5ac34f07f375cd1fe7cfb059534444ee3348eea9cca3d1ac'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'SHA256' '211d044d7a8d921cc9fbb4cf24938ca8f0a8e004fc21ffe2d63bd33c410cf936'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'SHA256' 'f93ecd0175147d99d50d80f28bba863e9bac4d7cfa482d5ade3dd7a0e3a70ec3'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'SHA256' '451a12939c9ac7625695f71028a872c0a201ae10429cf29f1fbe55bf637189b4'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'SHA256' '4fae97e66cc518023b764baab75c6699d225dc82277e5ad79650799ca3774231'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'SHA256' 'e210929979fdb0b785a3512b08a00326147a8062c68b4dec77d60766da856b6d'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'SHA256' '4c4eda09e17e8e79478281848f1da1c604636e8f5b0f31ec3625e0cec3b94edc'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'SHA256' '12cb3f99e1b575847ba8733eda17ddd01b998f2e9501f048aa520f70c36288c2'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'SHA256' '1f4d9141e7c651d38869d2c0add5ac85a532545436a016651193367119d7debb'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'SHA256' '011935775430a7ab84a72c364a07bfd0c8ecdfee8496f7fc8df5a1130fc0c323'
'prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/prsn/gn/v20200619/prsn_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'SHA256' 'd0f4079a4fd598f0ef4c8899f789f93f0167369fd03a81864a26132cdfc662ac'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 85 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
