#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2024/03/14 01:34:27
# Search URL: https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.pr.gn.v20200619|esgf-data1.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.llnl.gov/esg-search/wget?dataset_id=CMIP6.HighResMIP.MRI.MRI-AGCM3-2-S.highresSST-future.r1i1p1f1.day.pr.gn.v20200619|esgf-data1.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20150101-20151231.nc' 'SHA256' '045a627791752a89dbbfc00b927e4e3cf97c477afcd7902e61dfe5127fa72ef7'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20160101-20161231.nc' 'SHA256' '77dbc806067268e230eb39b40907e6a1374cd83a164701ab243cd5dd73e37a07'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20170101-20171231.nc' 'SHA256' 'a7d3843d73cf559ca1c8e407bb1f968b6dad52462f718d880fcce41f3af3d86c'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20180101-20181231.nc' 'SHA256' '1a2c819f5a2969755730a93ee368d3119b71f574be747ff7fbfbbfa7c0f0247d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20190101-20191231.nc' 'SHA256' '91fec7ca530410d8dbc8844ad82e13004e48f2a4d1af51f71fd3a556311b8a4c'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20200101-20201231.nc' 'SHA256' '998959f7fb2e3246d5c2f547e34d961e1dd44e07d8f9b10b4566ea8951ee6a9d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20210101-20211231.nc' 'SHA256' '5cd6b79dca5e6dd14203b02817c5354b6054480afb1ec9177f2ee33406ce4052'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20220101-20221231.nc' 'SHA256' '40d9bace9d3b6850e4e271365b99c2b31373329bc9097b7f337c19b4d864aa9c'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20230101-20231231.nc' 'SHA256' '59bc05c9eb6e577966098573580cc2ee8421f280e703af6f74fe524210b5acc8'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20240101-20241231.nc' 'SHA256' '532c5b04781be964a7a71ada93f8f98bfd4c957db9de3ee8c1c97ceeb05fcf8f'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20250101-20251231.nc' 'SHA256' '6afd785a1ef743a0adb3634dfa77ccfeb5092cc14e6f1ffdcb4c69ae05700b94'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20260101-20261231.nc' 'SHA256' '623e9e9bf03e00c3ea22b8cdc3f69755ef822950d2f80b2a7d1f9b68a315ec81'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20270101-20271231.nc' 'SHA256' 'd7a91c6327f99d5b80535452fe39774f31af721b9bad4afcea0cb474ccddb5ee'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20280101-20281231.nc' 'SHA256' '6fdb2e6c0645a8be9cde45e1a91e2ef7a18eb51162f833d22533a6e82bd661bf'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20290101-20291231.nc' 'SHA256' '8c652a0e58cf9756d3389873f78843441eec5c49ab6db50718beb794467895b3'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20300101-20301231.nc' 'SHA256' 'eee86b6f634020078190d177cd12d03ed476dc60902b2cafa72739467d923a9c'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20310101-20311231.nc' 'SHA256' '5efabe03cc6a0e86cd8a9429494bae566033d63fb5d04dcc96293a3f1df8b569'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20320101-20321231.nc' 'SHA256' '00c94895e21bfcb27584ea25737489dbcf88763610d5e7993dd471c0303b0d3a'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20330101-20331231.nc' 'SHA256' '52a24a486c6fdf0be201c9077dace889ac2c0628d85bc5082c2efc761fb4c438'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20340101-20341231.nc' 'SHA256' '7de7c6b7497c69c8b08edf89d25efe7c48eab43f05feacb0cdeb62196d475f4f'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20350101-20351231.nc' 'SHA256' '1d34e155bab18ad9f0007533d869c44174cadb649d7ed14d0161ab7c2e180ea1'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20360101-20361231.nc' 'SHA256' '6967bbe65cbb73b83b273c645aae87afa8bfd61c3c19be573f48a8326361cd67'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20370101-20371231.nc' 'SHA256' '6025fdf9b6b8696acc89a9581bdf3613fe2dd14ae6bd7069abd69f8d0af61cbf'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20380101-20381231.nc' 'SHA256' '5d2f1db6e776e211bc8046abb35378e856d33d532591a118c3bd213d9baf5b57'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20390101-20391231.nc' 'SHA256' 'd8cda67697358f8ddaddfb2f3348db28f11c79bc5db418b48f912b16324a570f'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20400101-20401231.nc' 'SHA256' '8ffd85beaf055ade178f57401d425ced6f72d22328ff92aa5e78ea21c5ed3fd1'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20410101-20411231.nc' 'SHA256' '70abf1c8cfc56fae76f4dbcf9c2fcc2b67e87430c3ea71e86d2c028976b9b759'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20420101-20421231.nc' 'SHA256' '9f5978b4f1af3d773c66e30c6aa0ae35536a0c7f9b53d4fee1615dbc4f8e81cd'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20430101-20431231.nc' 'SHA256' 'ca0d6fc20d3fb5fcfe92d0f3deac8bd2df1122fce8abed87bfba83fd2e928926'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20440101-20441231.nc' 'SHA256' '622c09fc2284a0d88fee23d6bc17ea24effca551376830781da56f83b98b0ab7'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20450101-20451231.nc' 'SHA256' '681ae7cf4a2a5075b7db47730da96d82cc497acf25529ea8933aa4255ae7f2e9'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20460101-20461231.nc' 'SHA256' 'f911cd8ed849bc5a514d5074883e471cbe0d605f9607d8584d576026a5811642'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20470101-20471231.nc' 'SHA256' '54d6147ec751901fd0446c7420434ef48d7f16b31531e69b8ddecd59bb484445'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20480101-20481231.nc' 'SHA256' '3d25435d747b0c7080f2520a37632a15eaac0ba48d6346b1b901a2b6a0327802'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20490101-20491231.nc' 'SHA256' '0cc1f979ee8c1155f5d63d5504999ed2dc8cd7459afa3721e4ac4fba2f0f7206'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20500101-20501231.nc' 'SHA256' '54a3b818d8b118e91c1c266833faea6b2af10a249e38a6190642f9cac9c088e0'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20510101-20511231.nc' 'SHA256' 'f5bb6e64381a54db851520601ad5bca14e667806c93e70cbf5035dcca28d00a9'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20520101-20521231.nc' 'SHA256' 'a6d0251a7c9bf64a677703938ce18e4ca0ffa9a77e1099d0ade7859356e66186'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20530101-20531231.nc' 'SHA256' '573864f61ac3fbbd3fbdd7fd9eed79df9e3faa73a0bb88b8c7da204600f81c8d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20540101-20541231.nc' 'SHA256' '7b069fd1f7c328eec9f3164dc9bc595706c68323fec53e9a9b367015e547e305'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20550101-20551231.nc' 'SHA256' 'c4025ff66b48e73b9d7d597525595ef9158d7f93b688fb164c151daddbed8ee1'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20560101-20561231.nc' 'SHA256' 'd52e51b8b339822148a38dfb7c705b003a067dc99e978c47dccce86a5c94725d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20570101-20571231.nc' 'SHA256' 'c490ea51be8b6533692699c13b2be69f2b60bfd07c14beb48aafde1af68ab35c'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20580101-20581231.nc' 'SHA256' 'f8d62457c04accb498c41afe23f3d2b77f90ae58ec17e2d5946cc14203f209dd'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20590101-20591231.nc' 'SHA256' '6cb053cb0f3310272d235babbed3058abed506b3fdd128bb8806156215c430c8'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20600101-20601231.nc' 'SHA256' '7ac803423c96dddfafd502e27f67c5a96728d2906643f5662c7b2393e5745ae5'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20610101-20611231.nc' 'SHA256' 'ead0cb18ddfa7cd1c476f4b010a76034539d0d189241af5852e9aa38c14d8644'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20620101-20621231.nc' 'SHA256' 'b72b9655223b4f87a78ebf39416e9c4158bdfaf9da6ce9fe374d2bc08b742127'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20630101-20631231.nc' 'SHA256' '91cae69a0caeebb094fdfae687f88c39b20a6d6aa4836323ea228e9271bb2979'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20640101-20641231.nc' 'SHA256' '28b7cdcf989eb6face59baa889a69fe760ade76432d6b499f089c68335efc90d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20650101-20651231.nc' 'SHA256' '060818232c523d208321bad05924a612e12c50a14b51c3037f637177dff54ced'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20660101-20661231.nc' 'SHA256' '193daf4496f03ebf8cd6d094d9a6e8803ac8ada6102b36c1e7e9393a779fdd47'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20670101-20671231.nc' 'SHA256' '2295f9bb7b1c2517c5d2f5711dc84141ba20a08f9ea34ed96de3b65386ba47b6'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20680101-20681231.nc' 'SHA256' '3445a905fd99dd6351ae0de571e2f20fb8648d49e26880c85ac6606c3b668077'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20690101-20691231.nc' 'SHA256' '38850c3cb8ade5f8166c45a14b44861273c9501ee72c2ceebf5bc1622f4b11ff'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20700101-20701231.nc' 'SHA256' 'e008155d52448291c763b7fe856f4f75150f3fb87455d50ce9c19de049cf3df2'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20710101-20711231.nc' 'SHA256' '7509e6ddc635a4d05e310bce043042c41016d40c4361edb60afa5542c14556c7'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20720101-20721231.nc' 'SHA256' 'aeb09a63aff70a5319256a671c299edf5e065f418035478d1af45c7bb85fd7ab'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20730101-20731231.nc' 'SHA256' '9e75f51a2699a8cbf688dc2a6a785c1cc5ce0ec3e72ccc5ba74d714860216178'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20740101-20741231.nc' 'SHA256' '4e528882f4adf0f4148be3bc341fefe2c52975cb8643bf10c08b2cf2b65cd0d3'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20750101-20751231.nc' 'SHA256' '5f3e89ab742245efb5c883085be4954b0a13404fb9e0c748954a3896f40672bb'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20760101-20761231.nc' 'SHA256' '70772547f1adb8cfe24799fab92c40db7cc1e8fa057690eeccff1ee95f6fd8a1'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20770101-20771231.nc' 'SHA256' 'c505e96a32fa6a8c8f10efd35241c3e74f9760afa57062c08604b066b829f564'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20780101-20781231.nc' 'SHA256' '150b9c4e11c0a216a08f82039ac1731cdce4059b702c606dd0304c7b0feaae92'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20790101-20791231.nc' 'SHA256' '595931469a6d92c89772a08aa1a896798d36c73a8a3dc2cd873da9983e10c1ee'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20800101-20801231.nc' 'SHA256' 'e04f4a28dc4bcfe716d50d7cf1d63625fcc19579e56f2ceef7f1883ea6b01e32'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20810101-20811231.nc' 'SHA256' '31d517c829cdebdc2630a7c71bf7c10f12780b7af9921c841a802e565da25353'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20820101-20821231.nc' 'SHA256' 'b57ede1ffccdeddac0aee0360805a8b6fb469d91036d3f23e5fc909193ff3559'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20830101-20831231.nc' 'SHA256' 'efee33f22d288f548a8823f6418b946fc6b6b03842923ffebea4e8f296c87723'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20840101-20841231.nc' 'SHA256' '04aa7a98568fa43fea2588c3f605a1e4353e0b09636d8e9e64bc38b76dc03ed1'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20850101-20851231.nc' 'SHA256' 'da03d31973e71cbfa14cb1496e0e5fe10c1b6080379e062802a7434cb7152f7b'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20860101-20861231.nc' 'SHA256' '77cd8b050a268cca25d5d9b7ce4f34ed2e870dd9f3153b3b1e3b1a3b2c45f8f9'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20870101-20871231.nc' 'SHA256' '92c01faa96dd6adbfceedf8f7e73aedf01b135254fcf3185cce520025b42ede9'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20880101-20881231.nc' 'SHA256' '7e2b5be78727cd586a28cf77e4078bf4623b756e8c709cbb75b2e2dcd03d7a3e'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20890101-20891231.nc' 'SHA256' '37b498588a10ad3d1f8a5a66acad189839d018281b0635be61bf451a92b86558'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20900101-20901231.nc' 'SHA256' '1b72c9a7abf681d728e69a83782b0f814cf815ed334c9e75ec475275bd404e50'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20910101-20911231.nc' 'SHA256' '0cd837743b73f2d7ba7d49bc8c9e065befcb02fcee02ef9cfbd3b3f2ddd4c369'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20920101-20921231.nc' 'SHA256' 'a40239f3f64c811cddbf876c043a7b259ef37242fbde6306fc392fd495216351'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20930101-20931231.nc' 'SHA256' '8c891d6e9004041b2d7231b1dc3f9f70c89c9a01c1eb3534054276046ca95d1d'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20940101-20941231.nc' 'SHA256' '9c09bc8058d67123ace573ec46c21c70a3483cd1647b2b04e9b9be4a393bc40e'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20950101-20951231.nc' 'SHA256' 'ef95816c62c9d8de665073d8e481efab4a5a1b7d034109c7bf38c351ba8343d0'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20960101-20961231.nc' 'SHA256' 'eb41e46e9e2a6d3bbd1a1db8d458bbe80b2ba6619821d01a3e878e8721a29507'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20970101-20971231.nc' 'SHA256' '9827e8fa430aa3dfc9c345610992ad9f1d7f1e6231b7cef88d88f336058179eb'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20980101-20981231.nc' 'SHA256' '62eb44bfa385e7d7051f3b241354980159d98eaee4270408a586c0863d35a354'
'pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/HighResMIP/MRI/MRI-AGCM3-2-S/highresSST-future/r1i1p1f1/day/pr/gn/v20200619/pr_day_MRI-AGCM3-2-S_highresSST-future_r1i1p1f1_gn_20990101-20991231.nc' 'SHA256' 'bc70355fe6712b8b02d580b820f723e2af48fdd06bda7c7918b4121ff6465dd6'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 85 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
